# Site settings
author: David Ryan Morphew
title: De Novo: Starting Fresh
header-img: img/home-bg.png
email: morphewd@umich.edu
copyright_name: David Ryan Morphew
description: > # this means to ignore newlines until "baseurl:"
  A 2000-year-ish Journey: From Humanities to Tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DavidRMorphew

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
